### PR TITLE
use localStorage for cache, marked as peerDep

### PR DESCRIPTION
**Pull request by caub**
- localStorage cache, that way we don't have to code it in each app
- reverted the configurable markdown parser, for now I think it's not necessary, if later it's needed we will put it, but for now, let's keep it simple, and compatible

@powmedia

### CODE REVIEW

**Comment by powmedia** [comment]
Having markdown separate and configurable outweigh the benefits of bundling - which were originally to be able to use it straight away without thinking about it, including when adding it to a web page without a build process etc.

Being able to choose your version and match it to what the app might already be using is worth keeping, especially as you only need to pass `markdown` as an option.  (When switching language you can just change it directly: `wurd.lang = 'de'`

For localStorage the changes in Store.js make sense, the idea eventually is that Store can be replaced with different implementations for e.g. server side use etc.  But will need to add some tests about expiry and also about skipping the cache in draft mode.

I'll also make some changes back to the wording etc. because that's something that is important to differentiate, for example when dealing with content items (e.g specific items of content of objects of nested content, vs. top level 'sections' of content).

**Comment by caub** [comment]
hmm ok, I don't want to annoy you more :) just wanted to make sure you're aware of the peerDependencies approach, it has the same benefit of skipping it from the bundle, or allowing multiple version
```
"peerDependencies": {
  "marked": ">=2"
}
```

no compatibility break, simpler setup, that we can focus on the more important thing about caching

**Comment by caub** [comment]
the wurd-web example/simple works if you load marked.min.js script before wurd.min.js

**Comment by caub** [comment]
Ok the caching part is finalized if you want some inspiration

**Comment by powmedia** [comment]
localstorage was added in https://github.com/wurdcms/wurd-web/pull/19

**Comment by powmedia** [comment]
Ah thanks, I've already been working on some more stuff here and handling
edge cases like editMode etc.  A few more bits to clean up later then I'll
publish a beta npm package so we can test more in depth

https://github.com/wurdcms/wurd-web/tree/lc-cache

**Pull request closed without merging**
