### PR TITLE
Fix load cache to support list of prefixes

### PR DESCRIPTION
**Pull request by caub**
@powmedia currently using `wurd.load()` with a comma-separated list of prefixes always miss the cache

This should fix it

### CODE REVIEW

**Comment by powmedia** [comment]
Ideally the load() method would in the same way as in the wurd-node module:
https://github.com/wurdcms/wurd-node/blob/master/src/index.js#L75

i.e. it tries to load as many of the `sections` as possible from the cache, and then only loads the remaining uncached sections from the server.

This way load() could be called many times and it doesn't matter if there are overlapping sections being requested

**Comment by powmedia** [comment]
I've been adding a couple of tests and updating rollup so will have a go at updating this

**Comment by caub** [comment]
I see what you mean, and we're doing this merge in  adminapp src/utils/cms-cache.js#L26

I'll move this logic there in here, because localStorage makes more sense than using memory, and expiry also is necessary, and that way no more need for this logic in admin app

**Comment by powmedia** [comment]
OK hold off for a bit as I've done some of this and am just finishing up tests etc.  Can think about adding localStorage as an option after that

Also considering removing built-in marked, which I think you suggested previously!

**Comment by caub** [comment]
ok, will catchup on it later, thanks

**Comment by caub** [comment]
I was thiking to remove store.js and move the logic in index.js, because if editMode is enabled it's probably better to disable cache

**Comment by powmedia** [comment]
Hmm I don't get github PRs!  Adding changes created a new branch so am going to merge from there https://github.com/wurdcms/wurd-web/pull/16

**Comment by caub** [comment]
yea it's not easy because the original branch is in my repo caub/wurd-web#fix-load-cache so you'd have to git pull that branch from a different git remote, and it's annoying, agreed

**Pull request closed without merging**
